language: 'en'
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'chore(release)'
    drafts: false
chat:
  auto_reply: true
