version: '3'

services:
  db:
    image: postgres:16-alpine
    container_name: honghongme-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=honghongme
  redis:
    image: redis
    container_name: honghongme-redis
    ports:
      - '6379:6379'

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: honghongme-redis-http
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: honghongme
      SRH_CONNECTION_STRING: 'redis://redis:6379'
